config/routes.rb
Fingerprints::Application.routes.draw do
  resources :action_items
  
  match '/dashboard/add_to_cart' => 'action_carts#add_to_cart'
  match '/dashboard/empty_cart' => 'action_carts#empty_cart'
  match '/dashboard/checkout_cart' => 'action_carts#checkout_cart'
  
  match '/dashboard/unlocked_achievements' => 'dashboard#unlocked_achievements'
  match '/dashboard/unlocked_achievements/:id' => 'dashboard#show_unlocked_achievement'  
  
  resources :performed_actions, :only => [ :create ]
  
  get "/dashboard" => 'dashboard#index'
  get "/dashboard/calendar" => 'dashboard#calendar', :as => :calendar

  root :to => 'home#index'

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/auth/failure' => 'sessions#failure'

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/signin' => 'sessions#new', :as => :signin

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # We don't want to use the default layout for our
	  # homepage.
    render :layout => false
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Fingerprints</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>

<body>

	<div class="topbar">
		<div class="fill">
			<div class="container">
				<a class="brand" href="#">Project name</a>
				<ul class="nav">
					<li class="active"><a href="#">Home</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="container">

		<!-- Main hero unit for a primary marketing message or call to action -->
		<div class="hero-unit">
			<h1>Achievements</h1>
			<p>A website without a name, yet. We'll use this space for maximum pitch action.</p>
			<p><a class="btn primary large" href="<%= signin_path %>">Login &raquo;</a></p>
		</div>

		<!-- Example row of columns -->
		<div class="row">
			<div class="span6">
				<h2>Heading</h2>
				<p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
				<p><a class="btn" href="#">View details &raquo;</a></p>
			</div>
			<div class="span5">
				<h2>Heading</h2>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
				<p><a class="btn" href="#">View details &raquo;</a></p>
			</div>
			<div class="span5">
				<h2>Heading</h2>
				<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
				<p><a class="btn" href="#">View details &raquo;</a></p>
			</div>
		</div>

		<footer>
			<p>&copy; Company 2011</p>
		</footer>

	</div>

</body>
</html>