config/routes.rb
Fingerprints::Application.routes.draw do
  resources :action_items
  
  match '/dashboard/add_to_cart' => 'action_carts#add_to_cart'
  match '/dashboard/empty_cart' => 'action_carts#empty_cart'
  match '/dashboard/checkout_cart' => 'action_carts#checkout_cart'
  
  match '/dashboard/unlocked_achievements' => 'dashboard#unlocked_achievements'
  match '/dashboard/unlocked_achievements/:id' => 'dashboard#show_unlocked_achievement'  
  
  resources :performed_actions, :only => [ :create ]
  
  get "/dashboard" => 'dashboard#index'
  get "/dashboard/calendar" => 'dashboard#calendar', :as => :calendar

  root :to => 'home#index'

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/auth/failure' => 'sessions#failure'

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/signin' => 'sessions#new', :as => :signin

end

app/models/action_item.rb
class ActionItem
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  
  belongs_to :action_group
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  # GET /action_items
  # GET /action_items.json
  def index
    @action_items = ActionItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @action_items }
    end
  end

  # GET /action_items/1
  # GET /action_items/1.json
  def show
    @action_item = ActionItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @action_item }
    end
  end

  # GET /action_items/new
  # GET /action_items/new.json
  def new
    @action_item = ActionItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @action_item }
    end
  end

  # GET /action_items/1/edit
  def edit
    @action_item = ActionItem.find(params[:id])
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(params[:action_item])

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render json: @action_item, status: :created, location: @action_item }
      else
        format.html { render action: "new" }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /action_items/1
  # PUT /action_items/1.json
  def update
    @action_item = ActionItem.find(params[:id])

    respond_to do |format|
      if @action_item.update_attributes(params[:action_item])
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item = ActionItem.find(params[:id])
    @action_item.destroy

    respond_to do |format|
      format.html { redirect_to action_items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_action_item.html.erb
<%= link_to image_tag("http://placehold.it/90x90&text=#{action_item.name}", :class => 'thumbnail'),
		{ :controller => "action_carts", :action => "add_to_cart", :action_item => action_item },
			:class => "btn"
%>

app/views/action_items/_form.html.erb
<%= form_for(@action_item) do |f| %>
  <% if @action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% @action_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing action_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<h1>Listing action_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @action_items.each do |action_item| %>
  <tr>
    <td><%= action_item.description %></td>
    <td><%= link_to 'Show', action_item %></td>
    <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
    <td><%= link_to 'Destroy', action_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Action item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New action_item</h1>

<%= render 'form' %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @action_item.description %>
</p>


<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>